name: ml4food
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
 - jupyter
 - matplotlib==3.7.1
 - numpy==1.21.*
 - pandas==1.5.2
 - python==3.10.9
 - openpyxl==3.0.10
 - scikit-learn==1.3.0
 - seaborn==0.12.2
 - umap-learn==0.5.3
 - ipywidgets==7.6.5