name: ml4food
dependencies:
 - blas==1.0
 - bottleneck==1.3.5
 - bzip2==1.0.8
 - ca-certificates==2023.01.10
 - certifi==2022.12.7
 - et_xmlfile==1.1.0
 - intel-openmp==2021.4.0
 - libffi==3.4.2
 - matplotlib==3.7.1
 - mkl==2021.4.0
 - mkl-service==2.4.0
 - mkl_fft==1.3.1
 - mkl_random==1.2.2
 - numexpr==2.8.4
 - numpy==1.23.5
 - numpy-base==1.23.5
 - openpyxl==3.0.10
 - openssl==1.1.1s
 - packaging==22.0
 - pandas==1.5.2
 - pip==22.3.1
 - python==3.10.9
 - python-dateutil==2.8.2
 - pytz==2022.7
 - scikit-learn==1.2.2
 - seaborn==0.12.2
 - setuptools==65.6.3
 - six==1.16.0
 - sqlite==3.40.1
 - tk==8.6.12
 - tzdata==2022a
 - vc==14.2
 - vs2015_runtime==14.27.29016
 - umap-learn==0.5.3
 - wheel==0.37.1
 - wincertstore==0.2
 - xz==5.2.10
 - zlib==1.2.13